marc-mabe/php-enum

src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php

Dynamic BitSet size, Getter Setter for BitSet

---

README.md

It's a subtle change, but showing some enum property assigned to a variable, and then using that variable as an object which has the `is()` method makes it a little clearer in my mind about how it could be used. i.e. no-one would bother to do `UserStatus::ACTIVE()->is(UserStatus::ACTIVE);` in real life code.

Documentation: Clarify is() usage

---

src/Enum.php

Corrected enumarator for enumerator.

Correct spelling

---

src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php

see #62
* ~~`EnumSet::getBitset() : string`~~
* ~~`EnumSet::setBitset(string $bitset)`~~
* `EnumSet::getBinaryBitsetLe() : string`
* `EnumSet::setBinaryBitsetLe(string $bitset)`
* `EnumSet::getBinaryBitsetBe() : string`
* `EnumSet::setBinaryBitsetBe(string $bitset)`

EnumSet: support for Little- and Big-Endian binary bitsets

---

src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php

see #62 Add methods to convert a set into an array
* `EnumSet::getEnumerators() : Enum[]`
* `EnumSet::getValues() : scalar[]`
* `EnumSet::getNames() : string[]`
@prolic I decided to use this names to be consistent with the already existing method `Enum::getEnumerators()` and I also return it just as lists so the ordinal number will not be the array key. I analyzed all my use-cases and couldn't find any where the ordinal number as array key is required. On the other hand I have some use-cases where I actually require a simple list. Also it's still simple possible to just use `iterator_to_array($set)` to convert the set into an associative array with ordinal number to enumerator instance.
PS: The same set of methods should also work on `EnumMap` and on `Enum` (as static versions)

EnumSet: added getEnumerators(), getNames() and getValues()

---

src/EnumSet.php

```
$ php bench.php 
empty set count(): 0.14792680740356ms
full set count() : 0.13878393173218ms
```
```
$ php bench.php 
empty set count(): 0.0060579776763916ms
full set count() : 0.10427093505859ms
```

optimized EnumSet::count()

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php
tests/MabeEnumTest/TestAsset/ConstVisibilityEnum.php
tests/MabeEnumTest/TestAsset/ConstVisibilityEnumExtended.php

PHP-7.1 will support [Class Constant Visibility](https://wiki.php.net/rfc/class_const_visibility)
but should `private` and/or `protected` class constants be part of an enumeration?

handle class constant visibility added in PHP-7.1

---

src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php

see #62 
These methods create a clone of `$this` and change the bitset to not depend on implementation details of extended classes. 
* `EnumSet::union(EnumSet ...$others) : EnumSet`
* `EnumSet::intersect(EnumSet ...$others) : EnumSet`
* `EnumSet::diff(EnumSet ...$others) : EnumSet`
* `EnumSet::symDiff(EnumSet ...$others) : EnumSet`

EnumSet: added methods union(), intersect(), diff() and symDiff()

---

src/Enum.php
tests/MabeEnumTest/EnumSerializableTraitTest.php
tests/MabeEnumTest/EnumTest.php

This static method was only for testing and on the same time it broke singleton behavior is used somewhere else as in this library tests. This removed all unnecessary usagas of it and rewrote necessary usages with reflection. So this cind of internal method is no longer needed and can be removed.

deprecated Enum::clear()

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php

… to be consistent with the object methods of EnumSet.

Added static Enum::getValues(), Enum::getNames() and Enum::getOrdinals()

---

README.md
src/Enum.php
src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php
tests/MabeEnumTest/EnumTest.php

This is just for consistency to differ the methods of getting something out of an enumeration/set/enumerator using `get*()` with the methods for accessing an enumerator (`Enum::by*()`).
The method `Enum::get($valueOrInstance)` still exists but I added the method `Enum::byValue($value)` which doesn't allow an already instantiated enumerator as argument.
-> So for consistency the method `Enum::get($valueOrInstance)` doesn't really follow this naming but calling it something like `byValueOrInstance` sounds stange to me and also this is a widely used method that I wouldn't like to rename.
@prolic Do you think this makes sense even with the given BC later on removing deprecated methods?

mv Enum::getBy[Name|Ordinal]() to Enum::by[Name|Ordinal]() & add Enum::byValue()

---

src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php
tests/MabeEnumTest/TestAsset/Enum66.php

... in EnumSet::setBinaryBitset*()

fixed logic of 'truncate out-of-range bits of last byte'

---

src/EnumSet.php

```
$before:
+----------------+------------------+--------+--------+------+-----+------------+---------+---------+---------+---------+---------+--------+------------+
| benchmark      | subject          | groups | params | revs | its | mem_peak   | best    | mean    | mode    | worst   | stdev   | rstdev | diff       |
+----------------+------------------+--------+--------+------+-----+------------+---------+---------+---------+---------+---------+--------+------------+
| EnumSet66Bench | benchGetOrdinals |        | []     | 2000 | 25  | 1,094,776b | 7.078μs | 7.190μs | 7.133μs | 7.449μs | 0.099μs | 1.38%  | +1,409.27% |
| EnumSet32Bench | benchGetOrdinals |        | []     | 2000 | 25  | 1,032,616b | 3.251μs | 3.334μs | 3.318μs | 3.452μs | 0.047μs | 1.40%  | +599.78%   | …
```

Optimized EnumSet::count() and EnumSet::getOrdinals()

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php

…by buffering a list of names per enumeration as `Enum::byOrdinal()` gets used a lot on `EnumSet`.
```
Before:
+----------------+----------------+--------+--------+------+-----+------------+----------+----------+----------+----------+---------+--------+-------------+
| benchmark      | subject        | groups | params | revs | its | mem_peak   | best     | mean     | mode     | worst    | stdev   | rstdev | diff        |
+----------------+----------------+--------+--------+------+-----+------------+----------+----------+----------+----------+---------+--------+-------------+
| EnumBench      | benchGetName   |        | []     | 2500 | 25  | 926,320b   | 21.671μs | 22.576μs | 22.803μs | 23.467μs | 0.478μs | 2.12%  | +5,068.79%  |
| EnumBench      | benchGetNames  |        | []     | 2500 | …
```

Optimized Enum::byOrdinal() and Enum::getName[s]() 

---

src/EnumMap.php
tests/MabeEnumTest/EnumMapTest.php

... and use PHP build-in hash impl. for performance reasons.
```
Current master:
+--------------+----------------------------------+--------+--------+------+-----+------------+----------+-----------+-----------+-----------+---------+--------+--------------+
| benchmark    | subject                          | groups | params | revs | its | mem_peak   | best     | mean      | mode      | worst     | stdev   | rstdev | diff         |
+--------------+----------------------------------+--------+--------+------+-----+------------+----------+-----------+-----------+-----------+---------+--------+--------------+
| EnumMapBench | benchOffsetSetEnumerator         |        | []     | 2000 | 25  | 1,113,928b | 61.552μs | 63.679μs  | 62.264μs  | 66.677μs  | 1.523μs | 2.39%  | +91,525.06%  |
| …
```

removed enumerator value support for EnumMap::getHash() 

---

README.md
bench/EnumMapBench.php
composer.json
src/Enum.php
src/EnumMap.php
src/EnumSet.php
tests/MabeEnumTest/EnumMapTest.php

* if data are serializable the `EnumMap` is serializable, too
* no longer based on `SplObjectStorage`
* no longer implement `Serializable`
* still implements `ArrayAccess`, `Countable` and `Iterator`
* new implements `SeekableIterator`
* Methods removed:
* `public function attach($enumerator) : void`
* please use `public function offsetSet($enumerator) : void`
* `public function detach($enumerator): void`
* please use `public function offsetUnset($enumerator) : void`
* `public addAll(SplObjectStorage $storage) : void`
* `public getHash(object $object) : string`
* `public removeAll(SplObjectStorage $storage) : void`
* `public removeAllExcept(SplObjectStorage $storage) : void`
* `public serialize(void) : string`
* `public setInfo(mixed $data) : void`
* `public unserialize(string …

Refactor EnumMap - fixes #91

---

.travis.yml
bench/EnumBench.php
bench/bootstrap.php
phpbench.json
phpunit.xml.dist
src/Enum.php
tests/MabeEnumTest/EnumTest.php
tests/bootstrap.php

... on checking for ambiguous enumerator values.
This will speed up first enumeration call with a factor of ~3.
The BC break is because of it throws an AssertionError if `zend.assertions = 1` or throws nothing.

Optimize Enum::detectConstants() by using assertion

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php

It allows the visibility keyword but ignores it.

HHVM >3.18.4 & >3.20.2 reports as PHP-7.1 but does not support constant visibility

---

src/Enum.php
src/EnumSet.php
tests/MabeEnumTest/EnumSetIteratorTest.php
tests/MabeEnumTest/EnumSetTest.php

```
+----------------+-------------------+--------------+--------------------+-----------------------+
| benchmark      | subject           | tag:4.x:mean | tag:generator:mean | tag:newInterator:mean |
+----------------+-------------------+--------------+--------------------+-----------------------+
| EnumSet66Bench | benchIterateFull  | 83.580μs     | 46.399μs           | 100.906μs             |
| EnumSet66Bench | benchIterateEmpty | 0.510μs      | 10.972μs           | 18.026μs              |
| EnumSet32Bench | benchIterateFull  | 33.086μs     | 18.721μs           | 41.721μs              |
| EnumSet32Bench | benchIterateEmpty | 0.401μs      | 3.688μs            | 7.150μs               |
+----------------+-------------------+--------------+--------------------+-----------------------+
``` …

EnumSet IteratorAggregate using Generator

---

bench/EnumBench.php
src/Enum.php
src/EnumMap.php
src/EnumSerializableTrait.php
src/EnumSet.php

Removed type-hints (except void) for private and final methods as this gives a small performance boost and this lib has enough tests to make sure it's working as expected.
Benchmark result:
```
+----------------+------------------------------+--------+--------+------+----------------+-------------------------+
| benchmark      | subject                      | groups | params | revs | tag:MAJOR:mean | tag:lessTypeHints_:mean |
+----------------+------------------------------+--------+--------+------+----------------+-------------------------+
| EnumSet66Bench | benchAttachEnumeratorOnEmpty |        | []     | 2000 | 30.783μs       | 28.493μs                |
| EnumSet66Bench | benchAttachValueOnEmpty      |        | []     | 2000 | 56.411μs       | 53.703μs                |
| …
```

Less type hints

---

README.md
bench/EnumSet32Bench.php
bench/EnumSet66Bench.php
src/EnumSet.php
tests/MabeEnumTest/EnumSetIteratorTest.php
tests/MabeEnumTest/EnumSetTest.php

Based on #108 
* implements `EnumSet` as immutable
* `attach(): void` -> `withEnumerator(): self`
* `detach(): void` -> `withoutEnumerator(): self`
* `setBit(): void` -> `withBit(): self`
* `setBinaryBitset[Le|Be](): void` -> `withBinaryBitset[Le|Be](): self`
PS 1: I still want to make some benchmarks for comparison
PS 2: This make sense only if we make `EnumMap` immutable too
@prolic ping

Immutable EnumSet

---

README.md
src/EnumMap.php
tests/MabeEnumTest/EnumMapTest.php

(similar to #110)
This gives a nice good performance improvement not only on iterating an `EnumMap` and reduces complexity. It also makes the iterator immutable due to changes happening to a map on iterating.
But the following BC breaks will happen:
* Generator::rewind() throws an exception as it's not supported after starting.
* the iterator is no longer seekable (it was seekable before via `SeekableIterator`)
* implements `IteratorAggregate` (instead of `SeekableIterator`)
Bench:
```
+--------------+-----------------------------+--------+--------+------+----------------+--------------------+
| benchmark    | subject                     | groups | params | revs | tag:4.x:mean   | tag:generator:mean |
+--------------+-----------------------------+--------+--------+------+----------------+- …
```

EnumMap IteratorAggregate using Generator

---

src/EnumMap.php
src/EnumSet.php
tests/MabeEnumTest/EnumMapTest.php

* added mutable methods
* `add($enumerator, $value)`
* `addIterable(iterable $map)`
* `remove($enumerator)`
* `removeIterable(iterable $enumerators)`
* (These methods are added for consistent naming - see #120)
* added immutable methods
* `with($enumerator, $value)`
* `withIterable(iterable $map)`
* `without($enumerator)`
* `withoutIterable(iterable $enumerators)`
* other changes
* added `get($enumerator)` : returns mapped data value or exception if missing
* `offsetGet($enumerator)` now returns `null` if missing - this change is done to be consistent with `offsetExists($enumerator)` which gets called by `isset` and should follow this behavior

Immutable EnumMap

---

src/Enum.php
src/EnumSerializableTrait.php
tests/MabeEnumTest/EnumSerializableTraitTest.php
tests/MabeEnumTest/EnumTest.php
tests/MabeEnumTest/TestAsset/ExtendedSerializableEnum.php

`Enum::__callStatic()` should call `static::byName()` instead of `self::byName()`.
Interestingly this never behaved wrongly but just because of a weird PHP behavior I have reported as a bug here https://bugs.php.net/bug.php?id=77985

Fix call static

---

README.md
src/EnumSet.php
tests/MabeEnumTest/EnumSetTest.php

Could be useful in situations where you want to know if 2 `EnumSet` intersects.

Add EnumSet::isEmpty() to know if sets has enumerators

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php

fixed check of ambiguous values on Enum::byName()

---

.gitattributes
.travis.yml
composer.json
psalm.xml
src/Enum.php
tests/MabeEnumStaticAnalysis/DummyEnum.php
tests/MabeEnumStaticAnalysis/EnumIsImmutable.php

This patch introduces a few improvements on the codebase:
* adds `vimeo/psalm` minimal tests (not testing sources, just declared API)
* adds `@psalm-pure` and `@psalm-immutable` to enumerable types, allowing usage of `Enum` in functionally pure (type-checked) contexts
* add better type declarations where refinements are possible (such as `non-empty-string` vs `string`, where applicable)
* removes some exported files from dist package (noticed because I wanted to exclude `psalm.xml` from exports)
I kept very conservative on type definitions: I wanted to restrict also on `::has()` and `::get()`, but that would introduce downstream issues, such as `::has($unknown)` failing due to missing upfront assertions.
Note: this is compatible with #138 too.

Added purity markers for enumerables, improved type definitions

---

src/EnumMap.php
src/EnumSet.php
tests/MabeEnumTest/EnumMapTest.php
tests/MabeEnumTest/EnumSetTest.php
tests/MabeEnumTest/TestAsset/EnumMapExt.php
tests/MabeEnumTest/TestAsset/EnumSetExt.php

* EnumSet: Add virtual private property "__enumerators" with a list of enumerator values set to the result of var_dump. This helps debugging as internally the enumerators of this EnumSet gets stored as either integer or binary bit-array.
* EnumMap: Add virtual private property "__pairs" with a list of key-value-pairs to the result of var_dump. This helps debugging as internally the map is using the ordinal number.

Added __debugInfo with human readable properties to EnumSet & EnumMap

---

.travis.yml
composer.json
phpstan.neon.dist
phpunit.xml.dist
src/Enum.php
src/EnumMap.php
src/EnumSerializableTrait.php
src/EnumSet.php
tests/MabeEnumStaticAnalysis/DummyEnum.php
tests/MabeEnumStaticAnalysis/EnumIsImmutable.php
tests/MabeEnumTest/EnumMapTest.php
tests/MabeEnumTest/EnumSerializableTraitTest.php
tests/MabeEnumTest/EnumSetIteratorTest.php
tests/MabeEnumTest/EnumSetTest.php
tests/MabeEnumTest/EnumTest.php
tests/MabeEnumTest/TestAsset/ConstVisibilityEnum.php
tests/MabeEnumTest/TestAsset/ConstVisibilityEnumExtended.php
tests/MabeEnumTest/TestAsset/Enum31.php
tests/MabeEnumTest/TestAsset/Enum32.php
tests/MabeEnumTest/TestAsset/Enum64.php
tests/MabeEnumTest/TestAsset/Enum65.php
tests/MabeEnumTest/TestAsset/Enum66.php
tests/MabeEnumTest/TestAsset/EnumBasic.php
tests/MabeEnumTest/TestAsset/EnumExtendedAmbiguous.php
tests/MabeEnumTest/TestAsset/EnumInheritance.php
tests/MabeEnumTest/TestAsset/EnumMapExt.php
tests/MabeEnumTest/TestAsset/EnumSetExt.php
tests/MabeEnumTest/TestAsset/ExtendedSerializableEnum.php
tests/MabeEnumTest/TestAsset/SerializableEnum.php
tests/bootstrap.php

* Introduces static code analyzes with PHPStan and psalm
* added generics using doc types for `EnumSet` and `EnumMap`
* Better doc types

Generics + better doc types PHPStan/psalm

---

src/Enum.php
tests/MabeEnumTest/EnumTest.php

In PHP8 it occurs this warning.
> Private methods cannot be final as they are never overridden by other classes
Caused by this PHP8 change https://wiki.php.net/rfc/inheritance_private_methods
`private` and `final` modifiers can't be used both.

final modifier for private method is no longer allowed in PHP8

---

.travis.yml
bench/bootstrap.php
composer.json
tests/bootstrap.php

* PHP-8 compatibility
* Restrict required PHP version to be ^7.1 or ^8.0 (before only the min version was defined)
* Removed assertion polyfill code in tests and bench bootstrap for php < 7.0
* this also fixes a segmentation fault running tests on PHP 8.0-rc

PHP-8 support

---

composer.json
psalm.xml
src/Enum.php
stubs/Stringable.php

Enum class has a __toString, so it would be great to implements the new Stringable interface.
As the interface is not available for php < 8, I've had the symfony/polyfill-php-80.
I've removed psalm `totallyTyped` attribute as it's now deprecated.

Implement Stringable interface on Enum

---

.github/workflows/test.Dockerfile
.github/workflows/test.yml
composer.json
phpstan.neon.dist
src/EnumMap.php
src/EnumSet.php
tests/MabeEnumTest/EnumSerializableTraitTest.php
tests/MabeEnumTest/EnumTest.php

* Run tests in PHP 8.2, 8.3 and 8.4
* fixed deprecation warning "implicitly nullable via default value null"
* fixed deprecation warning "Calling ReflectionProperty::setValue() with a single argument is deprecated"
* use xdebug instead of pcov

Fully support PHP 8.2, 8.3 and 8.4

---

src/Enum.php

Clearify serialization error message
